version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: quaterback_stats
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Adam1218
      POSTGRES_DB: Quaterback_Stats
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5332:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata

volumes:
  postgres_data:
